### ISSUE TITLE
clash 怎样设置  clash域名直连  clash韩国节点

### ISSUE THREAD

**Issue by clashvpn20** [clashvpn20/clashvpn#8]
推荐榜单1、爱连VPN
邀请好友注册充值返利高达40-50%
永久官网注册登陆网址：（打不开请点击下面导航）https://www.iovevpn.com/
永久导航：（最新网址进导航页面查找）https://www.ailianvpn.com/
爱连VPN手机下载（支持安卓-Winodws-MAC-苹果ios）https://www.ivpn.im
相比直连机场更加推荐购买中转机场。中转机场机器便宜一般更加带宽大，公网主要问题是出口偶尔会绕路导致网络波动影响。专线主要是不过墙延迟低，网络波动小，专线机场日常使用体验会更丝滑更舒服。机场比的是钞能力，速度要看机场的总带宽大小。稳定要看机场的资源质量，主要是看机场主的上游的线路质量，解锁看的是机场主的落地/解锁商是否优秀。机场带宽大和稳定性最重要。

### Clash 如何设置

**Clash 设置** 涉及到配置代理节点、规则、以及其他功能。以下是如何从头开始设置 Clash 的详细步骤。

#### **1. 下载和安装 Clash**

- **Windows**: 下载 Clash for Windows（CFW）。
- **macOS**: 下载 ClashX。
- **Linux**: 下载 Clash 的命令行版本。
- **Android/iOS**: 使用如 Shadowrocket、Quantumult 或 Clash for Android/iOS 等应用。

#### **2. 配置代理节点**

在 Clash 的配置文件中添加代理节点。以下是一个基本的配置示例：

```yaml
proxies:
  - name: "Korea-Proxy"
    type: ss
    server: korea.example.com
    port: 8388
    cipher: aes-256-gcm
    password: your_password

  - name: "Japan-Proxy"
    type: ss
    server: japan.example.com
    port: 8388
    cipher: aes-256-gcm
    password: your_password
```

#### **3. 配置代理组**

配置代理组以管理多个代理节点。以下是如何配置选择型代理组的示例：

```yaml
proxy-groups:
  - name: "Best-Proxy"
    type: select
    proxies:
      - Korea-Proxy
      - Japan-Proxy
```

#### **4. 配置规则**

定义规则以确定流量如何通过不同的代理组或节点：

```yaml
rules:
  - DOMAIN-SUFFIX,example.com,Best-Proxy
  - MATCH,Best-Proxy
```

#### **5. 导入和更新配置**

- **Clash for Windows/macOS**：在应用中导入配置文件，点击“更新”以应用配置。
- **Clash for Android/iOS**：在应用中导入配置文件，保存并更新。

### Clash 域名直连

**Clash 域名直连** 是指配置规则使特定的域名直接通过本地网络连接，而不经过代理。

#### **1. 配置直连规则**

在 Clash 的配置文件中，可以通过规则指定某些域名直连：

```yaml
rules:
  - DOMAIN-SUFFIX,example.com,DIRECT
  - DOMAIN-SUFFIX,anotherdomain.com,DIRECT
  - MATCH,Best-Proxy
```

在上面的示例中，`DIRECT` 关键字用于将所有匹配 `example.com` 和 `anotherdomain.com` 的流量直连，不经过任何代理。其他流量将使用 `Best-Proxy` 代理组进行转发。

#### **2. 配置全局直连**

如果你希望大多数流量都直接连接，可以在 `proxy-groups` 中配置全局直连：

```yaml
proxy-groups:
  - name: "Global"
    type: select
    proxies:
      - DIRECT
      - Korea-Proxy
      - Japan-Proxy

rules:
  - MATCH,DIRECT
```

在这个例子中，所有未匹配的流量都将通过 `DIRECT` 直连，而不是使用代理。

### Clash 韩国节点

**Clash 韩国节点** 是在配置文件中添加位于韩国的代理服务器。以下是如何设置韩国节点的步骤：

#### **1. 添加韩国节点**

在 Clash 配置文件的 `proxies` 部分添加韩国节点的详细信息：

```yaml
proxies:
  - name: "Korea-Proxy"
    type: ss
    server: korea.example.com
    port: 8388
    cipher: aes-256-gcm
    password: your_password
```

- **`name`**: 节点的名称
- **`type`**: 节点类型（如 `ss`、`vmess` 等）
- **`server`**: 韩国服务器的地址
- **`port`**: 端口号
- **`cipher`**: 加密方式
- **`password`**: 密码

#### **2. 配置代理组**

将韩国节点添加到一个代理组中，方便选择和管理：

```yaml
proxy-groups:
  - name: "Korea-Group"
    type: select
    proxies:
      - Korea-Proxy
      - Japan-Proxy
```

#### **3. 配置规则**

使用规则将特定流量路由到韩国节点：

```yaml
rules:
  - DOMAIN-SUFFIX,koreanwebsite.com,Korea-Proxy
  - MATCH,Korea-Group
```

在这个示例中，访问 `koreanwebsite.com` 的流量会通过 `Korea-Proxy`，其他流量会通过 `Korea-Group` 代理组中的节点进行处理。
