### ISSUE TITLE
clash域名伪装  clash规则分享  clash 默认端口

### ISSUE THREAD

**Issue by clashvpn20** [clashvpn20/clashvpn#9]
推荐榜单1、爱连VPN
邀请好友注册充值返利高达40-50%
永久官网注册登陆网址：（打不开请点击下面导航）https://www.iovevpn.com/
永久导航：（最新网址进导航页面查找）https://www.ailianvpn.com/
爱连VPN手机下载（支持安卓-Winodws-MAC-苹果ios）https://www.ivpn.im
相比直连机场更加推荐购买中转机场。中转机场机器便宜一般更加带宽大，公网主要问题是出口偶尔会绕路导致网络波动影响。专线主要是不过墙延迟低，网络波动小，专线机场日常使用体验会更丝滑更舒服。机场比的是钞能力，速度要看机场的总带宽大小。稳定要看机场的资源质量，主要是看机场主的上游的线路质量，解锁看的是机场主的落地/解锁商是否优秀。机场带宽大和稳定性最重要。

### Clash 域名伪装

**Clash 域名伪装** 是一种技术，用于隐藏真实的服务器域名，从而绕过网络过滤或审查。伪装可以通过配置 DNS 解析和域名混淆来实现。以下是如何在 Clash 中设置域名伪装：

#### **1. 配置域名混淆**

Clash 的配置文件允许你使用 DNS 解析规则来伪装域名。可以使用 `fake-ip` 或 `domain-set` 规则来实现混淆。

**示例配置**：

```yaml
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
  fallback:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
```

- **`enhanced-mode: fake-ip`**：开启 `fake-ip` 模式，以伪装 DNS 请求，避免直接暴露真实 IP 地址。
- **`nameserver`**：指定上游 DNS 服务器。

#### **2. 配置伪装规则**

在 `rules` 部分中配置伪装规则，以便对特定域名使用伪装技术。

**示例配置**：

```yaml
rules:
  - DOMAIN-SUFFIX,example.com,Fake-IP
  - DOMAIN-KEYWORD,proxy,Fake-IP
```

- **`DOMAIN-SUFFIX`** 和 **`DOMAIN-KEYWORD`**：匹配指定的域名后使用伪装 IP。

### Clash 规则分享

**Clash 规则分享** 指的是分享和使用预定义的规则集来管理网络流量。你可以从社区或网络上获取各种规则，并将其导入到你的 Clash 配置中。

#### **1. 获取规则**

你可以从以下来源获取 Clash 规则：

- **GitHub**：许多开发者和用户分享他们的 Clash 配置文件和规则集。
- **技术论坛和社区**：例如 Reddit、Telegram 群组等地方分享的规则集。
- **付费代理服务**：一些代理服务提供商提供预配置的规则集，作为其服务的一部分。

#### **2. 导入规则**

将获取的规则文件或规则集导入到你的 Clash 配置文件中：

**示例配置**：

```yaml
rules:
  - DOMAIN-SUFFIX,example.com,Proxy
  - DOMAIN-KEYWORD,video,Proxy
  - MATCH,DIRECT
```

**如何导入**：

- **Clash for Windows/macOS**：在应用的配置界面中导入规则文件。
- **Clash for Android/iOS**：通过应用中的配置选项导入规则文件。

### Clash 默认端口

**Clash 默认端口** 是 Clash 服务使用的默认网络端口。不同的 Clash 版本和应用可能使用不同的端口。

#### **1. Clash for Windows/macOS**

- **HTTP 代理**: 默认端口通常是 `7890`。
- **Socks5 代理**: 默认端口通常是 `7891`。
- **DNS**: 默认端口通常是 `53`。

#### **2. Clash for Android/iOS**

- **HTTP 代理**: 默认端口通常是 `7890`。
- **Socks5 代理**: 默认端口通常是 `7891`。

#### **3. 自定义端口**

你可以根据需要自定义端口。以下是如何在配置文件中自定义端口：

**示例配置**：

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
```

在配置文件中修改 `port`、`socks-port` 和 `redir-port` 值来调整 Clash 的端口设置。
